
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000/graphql
      - NSERVER=http://backend:4000/graphql
      - AUTH_SECRET=alskdjfsdghsdgsnddfhe

  backend:
    depends_on:
      - mongo
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret_here
      - EXPIRATION=2h
      - JOB_TYPES=Store_video
      - MONGODB_URI=mongodb://mongo:27017/CameraAdminDB
    volumes:
      - tempDownloads:/server/build/tempDownloads
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/CameraAdminSite  # 👈 persist data here
volumes:
  mongo-data:
  tempDownloads:
